### ISSUE TITLE
widgets merge when there's more then 1 on a page...

### ISSUE THREAD

**Issue by nandoptg** [tonysamperi/twits-fetcher#1]
trying to put 2 on a page - they each have their own unique Widget IDs, div IDs and uniqueIDs but they both end up in the last div each in their own twt-ct class...  anyway around that?

thanks in advance!

**Comment by tonysamperi** [comment]
Hello,


Do you have any demo online?



Tony Samperi






On Tue, May 24, 2016 at 2:04 PM -0700, "nandoptg" <notifications@github.com> wrote:





trying to put 2 on a page - they each have their own unique Widget IDs, div IDs and uniqueIDs but they both end up in the last div each in their own twt-ct class...  anyway around that?

thanks in advance!


---
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/tonysamperi/twits-fetcher/issues/1

**Comment by nandoptg** [comment]
Here you go: http://www.nova.edu/cwis/draft/bfernand/twitfetcher.html

**Comment by tonysamperi** [comment]
Now I see. You set two containers, but twits are rendered inside the last div.
I’ll let you know as soon as I find where the problem is.

Thank you

Best regards

Tony

**Comment by nandoptg** [comment]
thanks!

**Comment by nandoptg** [comment]
another thing I just noticed was the language... I changed it to english but it still seems to be in italian...

**Comment by tonysamperi** [comment]
Ok it’s almost done.

Thank you for your feedback.

**Comment by tonysamperi** [comment]
Hello,

I finally made it.
It was more complicated than it seemed.

The language problem was a consecuence of the main problem: the new widget overwrite also the settings of the old one,
because the old one is waiting for the AJAX Call.

Anyway, you can now download the updated version from github

https://github.com/tonysamperi/twits-fetcher

You can see from the demo page that now it’s possible to have multiple containers!

http://tonysamperi.github.io/twits-fetcher/

Thanks for your feedback

Best regards

Tony

**Comment by nandoptg** [comment]
awesome! thanks so much!

**Comment by tonysamperi** [comment]
Please, if you haven’t already, consider star-rating TwitsFetcher! Thank you
